apiVersion: v1
kind: Namespace
metadata:
  name: eshop
  labels:
    app.kubernetes.io/name: eshop
    app.kubernetes.io/instance: eshop

---
apiVersion: v1
kind: Service
metadata:
  namespace: eshop
  name: eshop-customer-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: eshop-customer-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eshop
  name: eshop-customer-api-deployment
  labels:
    app: eshop-customer-api
spec:
  selector:
    matchLabels:
      app: eshop-customer-api
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop-customer-api
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: eshop-customer-api
          image: maxmorev/eshop-customer-api:latest
          volumeMounts:
            - name: h2-storage
              mountPath: /opt/micro/h2
          ports:
            - containerPort: 8080
              name: springboot
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m" # 1/4 core
            limits:
              memory: "512Mi"
              cpu: "500m" # 1/2 core
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 70
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
      volumes:
        - name: h2-storage
          persistentVolumeClaim:
            claimName: pvc-customer