insert into customer (id,
                      address,
                      city,
                      country,
                      email,
                      fullname,
                      postcode,
                      authorities,
                      date_of_creation,
                      password,
                      verifycode,
                      verified,
                      shopping_cart_id)
values (10,
        'Address test',
        'Moscow',
        'Russia',
        'test@titsonfire.store',
        'Maxim V Morev',
        '111123',
        'CUSTOMER',
        '2019-08-25 18:46:23.918',
        '$2a$10$um0PcvHczmxeUEbR3vCBGuOvtNdgJffm72knavG/EFE7JDm9QBEha',
        'TKYOC',
        'f',
        null);

insert into customer (id,
                      address,
                      city,
                      country,
                      email,
                      fullname,
                      postcode,
                      authorities,
                      date_of_creation,
                      password,
                      verifycode,
                      verified,
                      shopping_cart_id,
                      reset_password_code)
values (15,
        'Address : test for update password',
        'Moscow',
        'Russia',
        'test-error@titsonfire.store',
        'Maxim V Morev',
        '111123',
        'CUSTOMER',
        '2019-08-25 18:46:23.918',
        '$2a$10$um0PcvHczmxeUEbR3vCBGuOvtNdgJffm72knavG/EFE7JDm9QBEha',
        'TKYOC',
        'f',
        13,
        'f6d56466-b345-11eb-8529-0242ac130003');


